### ISSUE TITLE
C++ exceptions question

### ISSUE THREAD

**Issue by eerimoq** [edubart/minicoro#2]
What's the reason for that C++ exceptions are not supported? What happens if an exception is thrown anyway? Would it be possible to add support for exceptions?

**Comment by edubart** [comment]
In short using exception you run the risk of breaking things.

C++ has three common exception models that depends in your compiler, architecture and platform:

* SEH (Structured Exception Handling)
* DWARF
* SJLJ (setjmp/longjmp)

They all work differently, they may vary even between compiler versions, perhaps some may work though I've not tested any as officially supporting them is not in the scope of the project. Usually the C++ compiler don't expect foreign changes in the control flow for these exceptions to behave correctly, but the context switching complete changes the control flow without the compiler noticing, thus I wouldn't be surprise to encounter issues. If all exception handler data is guaranteed to be stored within the coroutine stack I think they could work fine, but I've not researched whether this is true in all platforms, architecture and compilers.

But let me elabore an example where using exceptions is wrong:
```c++
#define MINICORO_IMPL
#include "minicoro.h"
#include <iostream>
#include <exception>

void coro_entry(mco_coro* co) {
  throw std::exception();
}

int main() {
  mco_desc desc = mco_desc_init(coro_entry, 0);
  mco_coro* co;
  mco_create(&co, &desc);
  try {
    mco_resume(co);
  } catch(std::exception& e) {
    std::cout << "got exception" << std::endl;
  }
  mco_destroy(co);
  return 0;
}
```
This example would be a common misuse of `try` with coroutines, because the exception is thrown inside the coroutine context it never propagate to its parent context, so the exception will never be cough and this is a crash.

However the above example is fixable by making sure the coroutine context catches all exceptions:
```C++
#define MINICORO_IMPL
#include "minicoro.h"
#include <iostream>
#include <exception>

void coro_entry(mco_coro* co) {
  try {
    mco_yield(co);
    throw std::exception();
  } catch(std::exception& e) {
    std::cout << "got exception" << std::endl;
  }
}

int main() {
  mco_desc desc = mco_desc_init(coro_entry, 0);
  mco_coro* co;
  mco_create(&co, &desc);
  mco_resume(co);
  mco_resume(co);
  mco_destroy(co);
  return 0;
}
```
This example seems to work fine on my x86_64 Linux GCC using DWARF exception model, but I cannot tell whether this will be true for other setups. To be safe I said that exceptions is not supported, you are on your own if you decide to use exceptions and should research more the implications of using them with context switching, and be responsible for testing target platforms and compilers.

**Comment by eerimoq** [comment]
Thanks!
